### ISSUE TITLE
Tirar meu nome do plugin

### ISSUE THREAD

**Issue by claudiosanches** [moskatus/Stelo-Woocommerce#1]
Hey cara, tudo bom?
Gostaria de saber se é possível tirar meu nome do plugin, tem gente me mandando e-mail fazendo perguntas e me cobrando de coisas desse plugin, ainda me chamando de mentiroso... Então se poder fazer esse favorzão, vou ficar muito grato.
Obrigado.

**Comment by moskatus** [comment]
Boa tarde Claudio tudo bem?

Desculpe cara, esse plugin foi descontinuado e devo ter usado como base o seu plugin da Cielo na época...

Vou exclui-lo.

Obrigado.

Atenciosamente,

Roney Moscato

________________________________
De: Claudio Sanches <notifications@github.com>
Enviado: Monday, February 25, 2019 12:13:17 PM
Para: moskatus/Stelo-Woocommerce
Cc: Subscribed
Assunto: [moskatus/Stelo-Woocommerce] Tirar meu nome do plugin (#1)


Hey cara, tudo bom?
Gostaria de saber se é possível tirar meu nome do plugin, tem gente me mandando e-mail fazendo perguntas e me cobrando de coisas desse plugin, ainda me chamando de mentiroso... Então se poder fazer esse favorzão, vou ficar muito grato.
Obrigado.

**Comment by claudiosanches** [comment]
@moskatus tudo tranquilo algum plugin meu como base e tudo mais, o problema é que como esta meu nome nele ainda, tem gente chegando em mim dizendo que é meu e me cobrando pra fazer ele funcionar xD
Obrigado pela ajuda.
